### ISSUE TITLE
Remove "hacked blocks" extention

### ISSUE THREAD

**Issue by KaneryU** [TurboWarp/extensions#1150]
Using for loops was better the way it was before and while <> loops were better before because they were automatically in the right category. The other blocks can stay as an extension. They are especially annoying because when you search for "join" in the middle click menu, the join image one comes up first, and it's not as useful as the for and while loops.

So, the for and while loops should be moved back to where they were before, and the other blocks can stay as an extension.

**Comment by CST1229** [comment]
The for loop [caused issues](https://github.com/TurboWarp/scratch-gui/issues/769), and the while loop still exists in Control.

**Comment by SurvExe1Pc** [comment]
The post title is misleading for what you are saying, and as CST said the for loop is broken. Also, both blocks are from experimental 2.0, I personally do not think this issue was needed, And the join issue is not our fault just don't use the extension if it bothers you that much.
________________________________
From: KaneryU ***@***.***>
Sent: Wednesday, November 15, 2023 9:03 PM
To: TurboWarp/extensions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TurboWarp/extensions] Remove "hacked blocks" extention (Issue #1150)


Using for loops was better the way it was before and while <> loops were better before because they were automatically in the right category. The other blocks can stay as an extension. They are especially annoying because when you search for "join" in the middle click menu, the join image one comes up first, and it's not as useful as the for and while loops.

So, the for and while loops should be moved back to where they were before, and the other blocks can stay as an extension.

**Comment by horizontal-shading** [comment]
I use while a lot
