### ISSUE TITLE
How to make auto update?

### ISSUE THREAD

**Issue by Qewbitech** [TurboWarp/extensions#1409]
I mean downloading file from internet to user device and may be start it. Are there any ideas?

**Comment by snowboyz0825** [comment]
There's probably a better way to do it, but the best way I can think of is to have every sprite in some file hosting service (i.e github) and have them all download via the Asset Manager extension. 

https://github.com/snowboyz0825/snowscodestuff/blob/main/SB3s/Dodge%20the%20dots%20loader.sb3

This loads every sprite in a project through github every time it's downloaded, and it "runs." (oh boy, giant red ERRORs) The issue is that variables and lists are not sprite specific, causing them to be reset. You could probably easily create a workaround for it, but this is an old project I'm not gonna relearn just for that. 

If there was an extension that allowed you to add a file using just it's data - which please let me know if you did because it would be very nice to know about - you could use some form of local storage to load it from that every time. 

I have no clue how this will play with compiled projects, but I imagine it isn't well

**Comment by CST1229** [comment]
> If there was an extension that allowed you to add a file using just it's data - which please let me know if you did because it would be very nice to know about - you could use some form of local storage to load it from that every time.

You can use data URLs with the Asset Manager extension.

**Comment by snowboyz0825** [comment]
I didn't know that data urls worked, in retrospect i should've tested that

**Comment by Qewbitech** [comment]
Good idea, I will check it today

**Comment by CubesterYT** [comment]
I'm assuming the answer is found.
