### ISSUE TITLE
[IDEA] We should make An Extension maker

### ISSUE THREAD

**Issue by unknown07724** [TurboWarp/extensions#1581]
it will use blocks and it will have a lot of them

**Comment by CubesterYT** [comment]
Use Turbo builder, which is a app made by someone else

**Comment by unknown07724** [comment]
it in development

**Comment by LilyMakesThings** [comment]
An "extension maker" would be a bad idea for a number of reasons. Let's start with the obvious: extension makers would only be capable of doing so much because of how complex and open-ended extension development is. The majority of extensions that would be made with it would be "Utility" extensions with blocks we've all seen before, and the people eagerly submitting them to the gallery would be quickly declined.

The limited scope of extensions made in the extension maker would also mean a lot of suggestions to add blocks to the maker that basically enable the development of someone's extension idea, when they could just learn the JavaScript themselves to make it. 

For instance, imagine someone wants to make an extension to print whatever is on the stage onto a piece of paper. They'd look for a "print () using printer" block and notice there isn't one. They'd ask for one on the Github issues page, someone else would research and implement the block, and then they'd use the block in their extension and submit it to the gallery. It's essentially putting the work of making an extension onto someone else, and when it isn't, it's derivative and boring.

Scratch, and moreso TurboWarp, offer in-editor solutions to making custom blocks that match the scope of what an "extension maker" would be able to create anyway: custom blocks. Better yet, in TurboWarp these are way faster because they don't run through a compatibility layer (unlike extensions) and are compiled straight to JS, so you're much better off using custom blocks anyway.

Also, I don't think the maintenance for what is essentially a second TurboWarp is worth it considering the bug bounty program and the fact we're all just volunteers. You have an extension maker in the form of custom blocks, use them.

**Comment by unknown07724** [comment]
allow most javascript methods(except Eval because) and all turbowarp APIs

**Comment by unknown07724** [comment]
first goal is getting the trio that is alert,confirm,prompt and other stuff like scroll,print

**Comment by namelessisbackbutnottodobadthingsiswear** [comment]
The problem is, for the time it'd take to implement _every javascript method_, it'd just be more worth it to implement it into an extension rather than add it to an arbitrary extension maker. Furthermore, if a user is able to understand javascript methods enough, they should probably just use javascript to make an extension.
While a custom extension maker would be cool, there's really no viable way to make work it without making itself redundant. As [lily said,](https://github.com/TurboWarp/extensions/issues/1581#issuecomment-2209382848), if you're just looking to make custom functions for your projects, you should really just use the already implemented custom blocks system (which is in essence just a more beginner-friendly version of extensions).

**Comment by RockyTheProtogen** [comment]
Hey, just going to chime in.
If anyone needs help on JavaScript, a great place for documentation is the MDN Web Docs.
And if you need an IDE, Visual Studio Code is a great option. And don't say you can't use it, as it has an online version too.

Put a little time in and you can make great things!
Remember to refer to the TurboWarp docs, too.
It is rather beginner friendly and a great way to start off a project.

An extension maker is great, but to put a little time and effort into true work is better.
You have the internet. That is all you need to start.

**Comment by unknown07724** [comment]
I never even knew that VScode had a online version

**Comment by CubesterYT** [comment]
TurboWarp won't ever make a extension maker. Either learn JS and our format to make extensions, or use the aforementioned third party website, TurboBuilder, to get what you want.

**Comment by unknown07724** [comment]
turbobuilder is in public beta And I don't want to have to deal with a million bugs

**Comment by RockyTheProtogen** [comment]
> turbobuilder is in public beta And I don't want to have to deal with a million bugs

Then use VSCode and find some guy on YouTube to help you.

**Comment by CubesterYT** [comment]
TurboBuilder has no bugs whatsoever. They're just testing and adding new stuff as they go. But there's been many people who made good extensions out of it.

**Comment by unknown07724** [comment]
+ they have a feature that only penguinmod will support that feature being the turbobuilder indicator

**Comment by RockyTheProtogen** [comment]
> ,+ they have a feature that only penguinmod will support that feature being the turbobuilder indicator

How is that an excuse to not use a perfectly good tool you have been given? You have been handed over a beautiful tool, and you turn your nose to it? You are better off using Visual Studio Code. Please just use one or the other.

**Comment by unknown07724** [comment]
welp I am doing it anyway, making on based on turbobuilder
