### ISSUE TITLE
[JSON extension] bug with get list and set list

### ISSUE THREAD

**Issue by Skyhigh173** [TurboWarp/extensions#268]
get list and set list can not be saved properly.

![7E6F5349-511B-48D0-AE32-E9D47F717811](https://user-images.githubusercontent.com/100467674/224539499-1f59607f-81a4-4aea-b057-df69845a4740.jpeg)
(get list (NOTES v) become (get list {…}) and can not work)

**Comment by Skyhigh173** [comment]
Will try to fix it

**Comment by GarboMuffin** [comment]
The problem is that your menus are storing name, ID, sprite ID, and whether the variable is local. Sprite IDs change every time the project runs, thus breaking your blocks.

The value `value` of your menus should just be the variable ID, and then you can use `util.target.lookupVariableById(id)` to find the variable.

You should also be setting `acceptReporters: true` for each of your menus https://docs.turbowarp.org/development/extensions/inputs#static-menus
