### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by HangWithCmm** [TurboWarp/extensions#28]
Could you add an option to immediately go to select a file location when uploading a file instead of the pop up?

Thanks

**Comment by CST1229** [comment]
I don't think this is possible in a website.

**Comment by GarboMuffin** [comment]
@HangWithCmm Can you explain what *exactly* you are trying to do? There is probably a better way to solve it than attempting to save files the user's computer in an arbitrary spot without telling them where.

**Comment by GarboMuffin** [comment]
What *exactly* are you trying to do with files, specifically?

**Comment by GarboMuffin** [comment]
> Could you add an option to immediately go to select a file location when downloading a file instead of the pop up?

Re-reading this, I'm very confused what you're trying to do. What does it mean to "immediately go to select a file location instead of the pop up" when downloading a file? Or did you mean opening a file?

**Comment by GarboMuffin** [comment]
I was confused because the original post says "download". We'll add a block to let you force the native file selector to immediately open, or at least try to. Sometimes the browser might still not let us.

**Comment by GarboMuffin** [comment]
Has been added

![image](https://user-images.githubusercontent.com/33787854/201499807-9615c7ac-b140-4d14-9327-2c6c06bb6251.png)

**Comment by GarboMuffin** [comment]
Doing that next

**Comment by GarboMuffin** [comment]
Electron has been updated. I have verified that the file extension issue is fixed.

For running extensions offline in packaged projects, follow https://github.com/TurboWarp/packager/pull/582

**Comment by GarboMuffin** [comment]
"follow" in this context means "check periodically to find out when it is implemented"

I'm hesitant to add a way to remove the prompt entirely because:

 - Browsers don't always let us open a file dialog, and they don't tell us when they refuse to, so the script would get stuck forever if there wasn't a way for people to manually open the dialog
 - Browsers don't reliably tell us when someone presses cancel on the dialog (only Firefox implement oncancel), so people need way to cancel the file dialog manually, otherwise the script gets stuck forever
 - Drag+drop is a very common way for people to select files

**Comment by GarboMuffin** [comment]
The linked pull request has been merged. The packager will attempt to fetch a copy of each extension ahead of time instead of each time the project runs, making it work offline and improving security.

**Comment by GarboMuffin** [comment]
You can now activate a mode like that by doing this:

![image](https://user-images.githubusercontent.com/33787854/201511034-651a949d-7fcb-463b-a41d-328fcf1c5674.png)

(the second text input there is completely empty, not even a space)

for the reasons mentioned previously, I don't recommend using this mode, so it hasn't been added to the dropdown at this time.
