### ISSUE TITLE
Fullscreen detection in Runtime Options extension

### ISSUE THREAD

**Issue by echoless3484** [TurboWarp/extensions#454]
Please add a fullscreen reporter in the Runtime Options extension, this would be so useful to change the size of the project depending if its fullscreen or not

**Comment by LukeManiaStudioss** [comment]
Assuming you're going tk package the project it'd be pretty pointless

**Comment by NDM1574** [comment]
> Assuming you're going tk package the project it'd be pretty pointless

It still wouldn't be useless, at 640x360 any project will have black bezels on the sides, only when in fullscreen mode will those be gone, but then if you set the resolution higher then it will have bezels but in fullscreen mode only.

An extension to this:
"is fullscreen?" reporter
"set [fullscreen] to [true, false]" extension to the main block that changes turbo mode, interpolation, and more

**Comment by NDM1574** [comment]
No, referring to the fullscreen button once packaged

**Comment by NDM1574** [comment]
Just bumping, this is really useful, the reason is we can make our own fullscreen buttons and change the resolution of the project, along with adjusting things automatically depending on if fullscreen is on or off, in 640x360 without fullscreen, the project has black bars on the sides, but stretching it makes everything, well... stretched, please add this lol
