### ISSUE TITLE
<Is (THIS) (Title Case v)> still not working

### ISSUE THREAD

**Issue by Ottiotta** [TurboWarp/extensions#475]
<img width="232" alt="image" src="https://github.com/TurboWarp/extensions/assets/124516852/0cc034c6-27a2-4262-ac5d-e99c611dc76f">
<img width="250" alt="image" src="https://github.com/TurboWarp/extensions/assets/124516852/3469b0e7-6692-493f-b7d0-d2d9ff155273">
Now is says true even if all of the text is uppercase

**Comment by GarboMuffin** [comment]
it works just fine

![image](https://github.com/TurboWarp/extensions/assets/33787854/caf0e607-2076-4c0c-ba29-6de7d3825ae5)

are you using the desktop app? it won't be updated there yet

**Comment by GarboMuffin** [comment]
(disregard previous deleted comment, misunderstood the issue)

this is because:

![image](https://github.com/TurboWarp/extensions/assets/33787854/8c428948-c03b-470e-968b-33f615dce57e)

which I think is perfectly fine behavior; converting "how to make a variable in JS" to title case should not lowercase the S in JS

what's the use case for knowing for changing this?

**Comment by GarboMuffin** [comment]
we could add something like "Exactly Title Case", but I do not expect that to be useful

**Comment by Ottiotta** [comment]
Make an list with common abbreviations and allow the user to edit it via blocks or any other way, the Title Case block will not convert that to title case nor will the Is Title Case return false if it meets that abbreviations, som common abbreviations is JS, CS, HTML

sorry for only programming languages, but i am a developer

**Comment by GarboMuffin** [comment]
Use the new "Exactly Title Case" option
