### ISSUE TITLE
scratch extension integration 

### ISSUE THREAD

**Issue by tigercoding56** [TurboWarp/extensions#772]
i have a idea as to how we can allow projects using custom extensions to be added to scratch ,
add a export to scratch button , it will prompt you   if the extensions are optional or mandatory , if they are mandatory it will add a sprite that pops-up prompting to use turbowarp if no turbowarp is found  , (and stopping all scripts) if not it is assumed the user has used the is_turbowarp block to use custom blocks to gain more features in turbowarp while still allowing code to work on scratch  ,   information about where costum blocks are is located in comment (as well as about extensions used), this would allow people to share advanced scratch projects using turbowarp blocks

**Comment by GarboMuffin** [comment]
my understanding is that the Scratch Team would not be a big fan of this

**Comment by tigercoding56** [comment]
> my understanding is that the Scratch Team would not be a big fan of this

why would they not be ?

**Comment by NexusKitten** [comment]
> > my understanding is that the Scratch Team would not be a big fan of this
> 
> why would they not be ? , it would generate more interest in scratch and it is not like these advanced features would be easily available to the 3 year olds

It's not exactly that Scratch doesn't want younger users to access the features, however the Scratch Team has certain visions for their platform they want to meet, and one of those visions is the site being self-contained. Doing this would provide a better alternative to the traditional Scratch editor, however would also require the use of a whole other website to access them. And like most things off-site, the Scratch team has the (valid) concern that it could be misused or mislead its users. Think browser extensions; although they provide objectively better features for Scratch, the Scratch Team has banned comment on them due to browser extensions being off-site.

**Comment by GarboMuffin** [comment]
1. not possible for technical reasons
2. if a large amount of projects start being uploaded to Scratch that are not compatible with Scratch (no matter how much we ask people to not do that, it is inevitable), the Scratch Team would probably be not happy (providing storage space for projects is not cheap!)
3. https://share.turbowarp.org/ will improve over time
