### ISSUE TITLE
Camera Lags Hard

### ISSUE THREAD

**Issue by Azulcat** [TurboWarp/extensions#802]
I tried my best (tick ,run without screen refresh) but the camera ext makes everything besides the player lag so hard that it hurts my eyes
Can someone help me?

https://github.com/TurboWarp/extensions/assets/134739700/882836a2-3867-4ef3-8815-428608ea25d9

**Comment by LilyMakesThings** [comment]
Do you have interpolation enabled?

**Comment by Azulcat** [comment]
ofc not @LilyMakesThings

**Comment by Azulcat** [comment]
got any way?

**Comment by CubesterYT** [comment]
Bro Camera Controls is a buggy mess :skull:

**Comment by NexusKitten** [comment]
Likely its not lagging, however it is an issue with Camera Controls. Essentially, the extension cannot set Camera X/Camera Y to a decimal, and so it'll always round up to the nearest integer. This can make the camera quality look really choppy at times. Unfortunately it's not an easy fix, I'd suggest either just accepting the choppiness or making your own camera system.

**Comment by Azulcat** [comment]
i made my own camera system it worked! but i hate it since all the sprite collision detection stops working and it is annoying i fixed it adding another sprite but i think that it makes everything hard @NexusKitten

**Comment by Azulcat** [comment]
@CubesterYT indeed lol

**Comment by penta-quark-neutro** [comment]
I see the camera pull back a bit.
If you use the method that I told you, you can achieve that instead of the camera being a little behind, it is a little forward.
I will pass examples.
the method that I showed you does that.
https://github.com/TurboWarp/extensions/assets/134885702/06818c5b-456b-4919-99e2-3088f6a4d54a
code.
![Captura de pantalla (233)](https://github.com/TurboWarp/extensions/assets/134885702/454293e2-19b3-4c44-887d-590f31b407bb)
To get the camera to do the opposite and then you can use the following.
![Captura de pantalla (234)](https://github.com/TurboWarp/extensions/assets/134885702/a870676b-b823-453c-bfd4-90c64fbd2e0c)
and that will give this result

https://github.com/TurboWarp/extensions/assets/134885702/2bc18f96-41d0-4242-a9d6-2203ca907340

**Comment by penta-quark-neutro** [comment]
Regarding the rest I read, the camera controls extension never gives me any problem.
And at least I see and have seen in my experiments that the position of the camera does accept decimals.

**Comment by Azulcat** [comment]
@NexusKitten but the cam values show me decimals

**Comment by GarboMuffin** [comment]
I am consolidating all the camera controls issues into https://github.com/TurboWarp/extensions/issues/930
